language: c

sudo: false

env:
  global:
    - CONDA_DEPENDENCIES="pytest numpy astropy"
  matrix:
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.3
    - PYTHON_VERSION=3.4
    - PYTHON_VERSION=3.5

install:
    - git clone git://github.com/astropy/ci-helpers.git
    - source ci-helpers/travis/setup_conda_$TRAVIS_OS_NAME.sh
    - python setup.py install

script:
   - cd tests
   - py.test --fits
   - python setup.py check --restructuredtext
